// sync-version.cjs
// Single source of truth for version info: version.json -> package.json + src/shared/app-info.ts
// 版本信息唯一权威来源：version.json 同步到 package.json 与 src/shared/app-info.ts
//
// Why package.json is still written: Electron app.getVersion(), electron-builder and npm
// all require the package.json version field; it becomes a synced artifact, not hand-maintained.
// [为何仍写 package.json：Electron app.getVersion()、electron-builder、npm 都依赖 package.json
// 的 version 字段；它变成同步产物，不再手工维护]
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const VERSION_JSON = path.join(ROOT, 'version.json');
const PACKAGE_JSON = path.join(ROOT, 'package.json');
const APP_INFO_TS = path.join(ROOT, 'src', 'renderer', 'core', 'app-info.ts');

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function main() {
  const ver = readJson(VERSION_JSON);
  const version = String(ver.version || '').trim();
  const codename = String(ver.internalCodename || '').trim();

  if (!/^\d+\.\d+\.\d+/.test(version)) {
    console.error('[sync-version] Invalid version in version.json:', JSON.stringify(ver));
    process.exit(1);
  }
  if (!codename) {
    console.error('[sync-version] Missing internalCodename in version.json');
    process.exit(1);
  }

  // 1. Sync package.json (keep 2-space indent + trailing newline) [同步 package.json (保持 2 空格缩进 + 末尾换行)]
  const pkg = readJson(PACKAGE_JSON);
  let changed = [];
  if (pkg.version !== version) { pkg.version = version; changed.push('version'); }
  if (pkg.internalCodename !== codename) { pkg.internalCodename = codename; changed.push('internalCodename'); }
  if (changed.length > 0) {
    fs.writeFileSync(PACKAGE_JSON, JSON.stringify(pkg, null, 2) + '\n');
  }

  // 2. Generate TS constants for the renderer domain only [仅为渲染层域生成 TS 常量]
  // Main process must NOT import this file: main & renderer tsconfigs share the same
  // outDir and would emit conflicting module formats (CJS vs ESM) to one path.
  // [主进程不得 import 此文件：主/渲染层 tsconfig 共用同一 outDir，会对同一路径
  // 输出冲突的模块格式 (CJS vs ESM)。主进程用 app.getVersion() 读取同步后的版本]
  const tsContent =
    `// Auto-generated by scripts/sync-version.cjs from version.json — do not edit [由 sync-version.cjs 从 version.json 生成，勿手改]\n` +
    `export const APP_VERSION = '${version}';\n` +
    `export const APP_CODENAME = '${codename}';\n`;
  fs.mkdirSync(path.dirname(APP_INFO_TS), { recursive: true });
  fs.writeFileSync(APP_INFO_TS, tsContent);

  console.log(`[sync-version] ${version} / ${codename} -> package.json${changed.length ? ` (updated: ${changed.join(', ')})` : ' (in sync)'} + src/renderer/core/app-info.ts`);
}

main();
